package ProductOrderOperations;

import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

public class StreamOperationsOnProductsOrders {

	public static void main(String[] args) {
		
		// 1. Get all orders placed via Mobile
		List<Order> orders = MockDataUtil.getMockOrders().stream().filter(o -> o.getSource().toLowerCase().contains("mobile"))
				.collect(Collectors.toList());
		System.out.println(orders);
		
		//to get count
		System.out.println(orders.size());
		
		//2nd way
		MockDataUtil.getMockOrders().stream().filter(o -> o.getSource().toLowerCase().contains("mobile"))
		.forEach(System.out::println);
		
		//fetch only orderIds
		List<String> orderIds = orders.stream().map(o -> o.getOrderId()).collect(Collectors.toList());
		System.out.println(orderIds);
		
		 System.out.println("---------------------------------------------");
		
		// 2. List all the product names
		List<String> productNames = MockDataUtil.getMockProducts().stream().map(n -> n.getProductName())
				.collect(Collectors.toList());
		System.out.println(productNames);
		
		 System.out.println("---------------------------------------------");
		 
		// 3. Count the number of orders placed for each product.
		 Map<Object, Long> noOfProductsPerOrders = MockDataUtil.getMockOrders().stream().
				 collect(Collectors.groupingBy(o -> o.getProductId(), Collectors.counting()));
		 System.out.println(noOfProductsPerOrders);
		 
		 System.out.println("---------------------------------------------");
		 
		// 4. Find the total revenue generated by "Gaming Keyboard" orders.
		 Product gamingProduct = MockDataUtil.getMockProducts().stream().filter(p -> p.getProductName()
				 .equalsIgnoreCase("gaming keyboard")).findFirst().get();
		 System.out.println(gamingProduct);
		 
		 Double revenueGeneratedByGamingKeyboard = MockDataUtil.getMockOrders().stream()
				 .filter(o -> o.getProductId().equals(gamingProduct.getProductId()))
				 .collect(Collectors.summingDouble(o -> o.getOrderAmount()));
		 System.out.println(revenueGeneratedByGamingKeyboard);
		 
		 System.out.println("---------------------------------------------");
		 
		//5. Get a distinct list of payment methods used in the orders.
		 List<String> paymentOptions =MockDataUtil.getMockOrders().stream()
				 .map(o -> o.getPaymentMode()).distinct().toList();
		 System.out.println(paymentOptions);
		 
		 System.out.println("---------------------------------------------");
		 
		//6. Get the top 2 products with the highest price.
		 List<Product> top2Products = MockDataUtil.getMockProducts().stream()
				 .sorted((p1, p2) -> p1.getPrice() < p2.getPrice() ? 1 : -1)
				 .limit(2).toList();
		 System.out.println(top2Products);
		 
		 System.out.println("---------------------------------------------");
		 
		 //to get top product
		 Product highestPrice = MockDataUtil.getMockProducts().stream()
				 .max(Comparator.comparingDouble(Product::getPrice)).orElse(null);
		 System.out.println(highestPrice);
		 
		 System.out.println("---------------------------------------------");
		 
		// 7.For each product, find total quantity sold across all orders.
		 Map<String, Integer> orderPerProduct = MockDataUtil.getMockOrders().stream()
				 .collect(Collectors.groupingBy(o -> o.getProductId(), Collectors.summingInt(p -> p.getQuantity())));
		 System.out.println(orderPerProduct);
		 
		 System.out.println("---------------------------------------------");
		 
		//8️ Find the product whose total revenue is highest.
		 
		 //a.form map of product id and product name
		 Map<String, String> productIdNameMap = MockDataUtil.getMockProducts().stream()
				 .collect(Collectors.toMap(Product::getProductId, Product::getProductName));
		 System.out.println(productIdNameMap);
		 
		 //b. to get the product with highest revenue from above map
		 String productNameString  = MockDataUtil.getMockOrders().stream()
		 .collect(Collectors.groupingBy(o -> o.getProductId(), Collectors.summingDouble(p -> p.getOrderAmount())))
		 .entrySet().stream()
		 .max(Map.Entry.comparingByValue())
		 .map(p -> productIdNameMap.get(p.getKey())).orElse("");
		 
		 System.out.println(productNameString);
		 
		 //to fetch product with total revenue
		 Map<Object, Double> productWithHighestRevenue = MockDataUtil.getMockOrders().stream()
				 .collect(Collectors.groupingBy(p -> p.getProductId(), Collectors.summingDouble(p -> p.getOrderAmount())));
		 System.out.println(productWithHighestRevenue);
		 
		 System.out.println("---------------------------------------------");
		 
		//9. Detect duplicate orders (same orderId) and list them.
		 //Map<String, List<Order>> orders1 = MockDataUtil.getMockOrders().stream()
		 //										.collect(Collectors.groupingBy(o -> o.getOrderId()));
		 //System.out.println(orders1);
		 
		 List<Order> duplicateOrders = MockDataUtil.getMockOrders().stream().collect(Collectors.groupingBy(o -> o.getOrderId()))
		 .entrySet().stream()
		 .filter(map -> map.getValue().size() > 1)
		 .flatMap(o -> o.getValue().stream()).collect(Collectors.toList());
		 
		 System.out.println(duplicateOrders);
		 
		 //to print just duplicate order ids
		 List<String> duplicateOrderIds = MockDataUtil.getMockOrders().stream().collect(Collectors.groupingBy(o -> o.getOrderId())) //groups ordersby orderId
		 .entrySet().stream()
		 .filter(entry -> entry.getValue().size() > 1) //only entries with duplicates
		 .map(entry -> entry.getKey()) //Extract just the orderId
		 .collect(Collectors.toList()); //collects into list
		 
		 System.out.println(duplicateOrderIds);
		 
		 
		 
		 
		 
	}

}
